---
abstract: 'Serialize RDF graphs as dot graph diagrams'
author:
  - 'Jakob Voß <voss@gbv.de>'
build_requires:
  English: 0
  Test::More: 0
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200012, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RDF-Trine-Serializer-GraphViz
requires:
  Carp: 0
  Getopt::Long: 0
  GraphViz: 0
  RDF::Trine: 0
  RDF::Trine::Model: 0
  RDF::Trine::Parser: 0
  RDF::Trine::Serializer: 0
  Scalar::Util: 0
resources:
  bugtracker: https://github.com/nichtich/RDF-Trine-Serializer-GraphViz/issues
  repository: https://github.com/nichtich/RDF-Trine-Serializer-GraphViz
version: 0.002
